# Generated by Django 6.0.2 on 2026-02-14 21:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('estimated_price', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='StoreRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('store', 'Nouvelle Boutique'), ('product', 'Nouveau Produit')], max_length=10)),
                ('store_name', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_url', models.URLField(blank=True, null=True)),
                ('contact_person', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('h2_title', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/sections/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='blog/banners/')),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.blogpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, max_length=100, null=True)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('screen', models.CharField(blank=True, max_length=100, null=True)),
                ('battery', models.CharField(blank=True, max_length=100, null=True)),
                ('audio', models.CharField(blank=True, max_length=100, null=True)),
                ('camera', models.CharField(blank=True, max_length=100, null=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='api.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='BlogSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advantages', models.TextField()),
                ('disadvantages', models.TextField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='api.blogpost')),
            ],
        ),
    ]
